VERSION --shell-out-anywhere --use-cache-command --use-copy-include-patterns --use-host-command 0.6
FROM golang:1.19-alpine
IMPORT ../../ AS root

root-artifacts:
  FROM DOCKERFILE .
  COPY root+artifact/artifacts/*1 artifacts/
  RUN ls artifacts
  RUN cat docker

