VERSION 0.6
FROM golang:1.19-alpine
IMPORT ../ AS root

GREET:
  COMMAND
  RUN echo "Hello foo"

artifact:
  RUN echo "fooo"> artifact
  SAVE ARTIFACT artifact

greet:
  ARG name
  DO ../+GREET --name=$name

root-artifact:
  COPY root+artifact/artifact artifact
  RUN cat artifact

